<?php 
if(!defined('VERSION')) {
  header('Location:/');
  exit();
}
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta  charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <!-- <meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1, width=device-width"> -->
  <!-- <meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" > -->
  <meta http-equiv="Content-Type" content="text/html;" />
  <meta name="description" content="主页" />
  <meta name="renderer" content="webkit">
  <title><?php echo $this->view['title'] ?></title>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <!-- jQuery文件-->
  <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
  <!-- 新 Bootstrap 核心 CSS 文件 -->
  <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
  <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="/css/header-footer.css" />
  <link rel="stylesheet" type="text/css" href="/css/index.css" />
  <script type="text/javascript" src="/js/index.js"></script>
  <script type="text/javascript" src="/js/header-footer.js"></script>
</head>
<body>
  <?php include $this->view['header']; ?>
  <div class="jumbotron">
    <table border="1" class="table">
    <tr>
      <th><p class="text-center">序号</p></th>
      <th><p class="text-center">name</p></th>
      <th><p class="text-center">value</p></th>
      <th><p class="text-center">autoload</p></th>
    </tr>
    <?php foreach ($this->view['options'] as $option): ?>
      <tr>
        <td><p class="text-center"><?php echo $option['id']; ?></p></td>
        <td><p class="text-center"><?php echo $option['name']; ?></p></td>
        <td><p class="text-center"><?php echo $option['value']; ?></p></td>
        <td><p class="text-center"><?php echo $option['autoload']; ?></p></td>
      </tr>
    <?php endforeach; ?>
    </table>

    <br />
    <table border="1" class="table">
    <tr>
      <th><p class="text-center">序号</p></th>
      <th><p class="text-center">name</p></th>
      <th><p class="text-center">path</p></th>
      <th><p class="text-center">group</p></th>
      <th><p class="text-center">description</p></th>
    </tr>
    <?php foreach ($this->view['images'] as $image): ?>
      <tr>
        <td><p class="text-center"><?php echo $image['img_id']; ?></p></td>
        <td><p class="text-center"><?php echo $image['img_name']; ?></p></td>
        <td><p class="text-center"><?php echo $image['img_path']; ?></p></td>
        <td><p class="text-center"><?php echo $image['img_group']; ?></p></td>
        <td><p class="text-center"><?php echo $image['description']; ?></p></td>
      </tr>
    <?php endforeach; ?>
    </table>
  </div>
    <div class="bgm">
      <audio src="/static/music/inuyasha_bgm.mp3" controls="controls" autoplay="autoplay" loop="loop">
        您的浏览器不支持 audio 标签。
      </audio>
    </div>
  <?php include $this->view['footer']; ?> 
</body>
</html>