<?php 
  if(!defined('VERSION')) {
    header('Location:/');
  }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>get IP</title>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <!-- <link rel="stylesheet" type="text/css" href="/css/index.css" />
  <link rel="stylesheet" type="text/css" href="/css/header.css" />
  <link rel="stylesheet" type="text/css" href="/css/footer.css" /> -->
  <script type="text/javascript" src="/js/jquery-1.12.1.min.js"></script>
  <!--  <script type="text/javascript" src="/js/index.js"></script> -->
</head>
<body>

  <a href="http://www.ip138.com/"  target="_blank">中国最大的、最权威的IP数据库</a>
  <form METHOD=get ACTION="http://www.ip138.com/ips1388.asp" name="ipform" target="">
    <tr>
      <td align="center">IP地址：<input type="text" name="ip" size="16" value="<?php echo $_SERVER['REMOTE_ADDR']?>"> 
      <input type="submit" value="查询"><INPUT TYPE="hidden" name="action" value="2">
      </td>
    </tr>
  </form>
  
</body>