<?php 
  if(!defined('VERSION')) {
    header('Location:/');
    exit();
  }
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta  charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Content-Type" content="text/html;" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
  <!-- <link rel="stylesheet" type="text/css" href="/css/index.css" /> -->
  <!-- jQuery文件-->
  <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
  <!-- 新 Bootstrap 核心 CSS 文件 -->
  <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
  <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="/css/header-footer.css" />
</head>
<body>
  <?php include $this->view['header']; ?> 
  <div class="container">
    <?php $this->view_info_content($view);?>
  </div>
  <?php include $this->view['footer']; ?>
</body>
</html>