<?php 
if(!defined('VERSION')) {
  header('Location:/');
  exit();
}
// require_once CORE_PATH.'const.php';
?>
<div id="header">
  <div class="z_top">
    <div class="head-mask top">
      
    </div>
    <div class="container">
      <div class="navbar-header">
        <a class="logo" href="/"><img src="<?php echo $this->view['logo']; ?>" alt="SunSmell" /></a>
      </div>
      <!-- <span class="title" >个人主页</span> -->
      <div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
        <div class="navbar-right">
          <div class="btn-group navbar-btn-group btn-group-lg" role="group">
            <button type="button" class="btn btn-primary" disabled="disabled">button1</button>
            <button type="button" class="btn btn-primary" disabled="disabled">button2</button>
          </div>
        </div>
        <a href="#" class="navbar-right">
          <img class="img-circle avatar" src="<?php echo $this->view['avatar']; ?>" alt="avatar">
        </a>
      </div>
    </div>
  </div>
</div>