<?php 
if(!defined('VERSION')) {
  header('Location:/');
  exit();
}
?>
<!DOCTYPE html>
<html lang="zh-CN" PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<head>
  <meta  charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=1, user-scalable=0">
	<meta http-equiv="Content-Type" content="text/html;" />
	<meta name="description" content="主页" />
  <meta name="renderer" content="webkit">
  <title>sunsmell主页</title>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
  <!-- jQuery文件-->
  <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
  <!-- 新 Bootstrap 核心 CSS 文件 -->
  <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
  <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="/css/header-footer.css" />
  <link rel="stylesheet" type="text/css" href="/css/index.css" />
  <script type="text/javascript" src="/js/index.js"></script>
</head>
<body>
  <?php include $this->view['header']; ?>
  <!-- <div class="jumbotron"> -->
  <div id="carousel-index" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-index" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-index" data-slide-to="1"></li>
    <li data-target="#carousel-index" data-slide-to="2"></li>
  </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/static/img/sword_art_online_4.jpg" alt="图片1">
        <div class="carousel-caption">
          这只是一组烧流量的图片
        </div>
      </div>
      <div class="item">
        <img src="/static/img/sword_art_online_2.jpg" alt="图片2">
        <div class="carousel-caption">
          这只是一组烧流量的图片
        </div>
      </div>
      <div class="item">
        <img src="/static/img/sword_art_online_3.jpg" alt="图片3">
        <div class="carousel-caption">
          这只是一组烧流量的图片
        </div>
      </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-index" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-index" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="container marketing">
    <div class="row">
      <div class="col-lg-4">

      </div>
      <a class="" href="<?php 
      #echo '/?action=ext&cat=wordpress';
      echo '/wordpress'; # ?>">
        <div class="col-lg-4 col-link-item">
          <h2>My Blog</h2>
          <p>my blog with wordpress</p>
        </div>
      </a>
      <div class="col-lg-4">

      </div>
    </div>
    <?php if(DEBUG_MODE):?>
    <div class="alert alert-warning">
      <p class="text-left">该网站还有很多东西没有完工！<br /></p>
    </div>  
    <?php endif;?>
  </div>
  <?php include $this->view['footer']; ?> 
</body>
</html>